### ISSUE TITLE
In client hooks context from RequestPrepared is not received in ResponseReceived

### ISSUE THREAD

**Issue by mspindelhirn** [twitchtv/twirp#250] opened 2020-07-13 16:53 UTC
As `callClientRequestPrepared` is called within `doProtobufRequest` and that function does not return the context the context provided to `ResponseReceived` "only" has the values from the generated RPC client call and everything prior to that but nothing from inside `doProtobufRequest`.

**Comment by dpolansky** [comment] 2020-07-13 23:32
Hey @mspindelhirn, I'm having trouble understanding this issue. From [this generated example code](https://github.com/twitchtv/twirp/blob/03ac4c78b781f6a1e5f0ff79486bff15f6596a4f/example/service.twirp.go#L850), it looks like the request context is properly passed to the `RequestPrepared` hook, and then the result from the hook is returned from here. Can you provide additional detail?

**Comment by dpolansky** [comment] 2020-07-14 19:18
@mspindelhirn I've confirmed with some folks that this is definitely a bug. Are you interested in submitting a fix for this? If not, I'm happy to take care of it.

**Comment by mspindelhirn** [comment] 2020-07-15 06:58
Thanks for the follow up.

I can definitly have a go at this and try to provide a fix sometimes this week.

**Closed** 2020-07-24 16:59 UTC
