### ISSUE TITLE
Context setters don't work when imported packages' vendor directories are not flattened

### ISSUE THREAD

**Issue by kminehart** [twitchtv/twirp#94] opened 2018-03-27 18:27 UTC
I have an external service called "Metadata", which is a twirp server.

Here's a small test app I wrote to try to send it an HTTP header, basically following the example in the wiki verbatim.

```go
package main

import (
	"context"
	"log"
	"net/http"
	"os"

	pb "git.example.io/rune/rune/metadata/rpc"
	"github.com/twitchtv/twirp"
)

var (
	twirpContext = context.Background()
)

func init() {
	header := make(http.Header)
	log.Println(header)
	header.Set("Example-Authorization", "testing")
	var err error
	twirpContext, err = twirp.WithHTTPRequestHeaders(twirpContext, header)
	if err != nil {
		log.Panicln("Error attaching headers to twirp context: ", err.Error())
	}
}

func main() {
	log.Println(twirpContext)
	exampleClient := pb.NewMetadataProtobufClient(os.Getenv("RUNE_METADATA_ADDRESS"), &http.Client{})
	exampleClient.Get(twirpContext, &pb.GetMetadataRequest{})
}

```

Log output:

```
2018/03/27 13:17:23 map[]
2018/03/27 13:17:23 context.Background.WithValue(5, http.Header{"Example-Authorization":[]string{"testing"}})
```

Here is the request being logged when Go / twirp is used:

```
...metadata.Metadata/Get] Headers: map[Content-Type:[application/protobuf] Twirp-Version:[v5.2.0] Accept-Encoding:[gzip] X-Envoy-Internal:[true] X-Envoy-Expected-Rq-Timeout-Ms:[5000] User-Agent:[Go-http-client/1.1] Content-Length:[0] X-Forwarded-Proto:[https] X-Request-Id:[eb43abc0-bbe9-4d7e-9f37-f709e82949e1] X-Ambassador-Calltype:[extauth-request] X-Forwarded-For:[10.24.5.119]]
```
You'll notice `Twirp-Version` is there, but not `Example-Auth`.

But when I use curl:

```
curl -L -v -X POST -H "content-type: application/json" -d '{"test":"req"}' -H "Example-Authorization: testing" https://api.example.io/metadata/v1/twirp/example.metadata.Metadata/Get
```

```
...metadata.Metadata/Get] Headers: map[Content-Length:[0] X-Forwarded-Proto:[https] X-Ambassador-Calltype:[extauth-request] X-Forwarded-For:[10.24.5.119] User-Agent:[curl/7.59.0] Accept:[*/*] Content-Type:[application/json] Example-Authorization:[testing] X-Request-Id:[2177d537-6079-42fb-9dd9-15c0e96feb25] X-Envoy-Internal:[true] X-Envoy-Expected-Rq-Timeout-Ms:[5000]]
```

To me, the fact that it works with curl but not Twirp says that the problem is that twirp is not including the headers in the request.

Edit: This happens regardless of what the content-type is set to. (pb.NewMetadataProtobufClient vs pb.NewMetadataJSONClient)

**Comment by kminehart** [comment] 2018-03-27 21:58
I added some logging to my generated client:

I printed my `context` that was passed to `func getCustomHTTPReqHeaders(ctx context.Context)`:

```
2018/03/27 16:54:40 context.Background.WithValue(5, http.Header{"Example-Authorization":[]string{"testing"}}).WithValue(3, "example.metadata").WithValue(2, "Metadata").WithValue(1, "Get")
```

And I printed what it returned when it called `twirp.HTTPRequestHeaders`

```
2018/03/27 16:54:40 twirp.HTTPRequestHeaders returned (ok: false / header: map[]); ignoring...
```

I'm going to create a fork and add some tests for `twirp.HTTPRequestHeaders` and hopefully I can find the issue.

**Comment by kminehart** [comment] 2018-03-28 03:31
Update!

We had `github.com/twitchtv/twirp` in our `vendor` folder at `v5.3.0`.

Removing that package from the `vendor` folder fixed the problem. Sort of. It's not really a fix, but it's a good indicator of what the problem might be.

**Comment by zikes** [comment] 2018-03-28 04:13
Turns out it's because the test application is located outside of the parent project, under which twirp is vendored. The test application imports `github.com/twitchtv/twirp` (i.e. under `$GOPATH/src`) while `git.example.io/rune/rune/metadata/rpc` imports `git.example.io/rune/rune/vendor/github.com/twitchtv/twirp`, and a mismatch somewhere (my money is on `contextkeys`) causes HTTPRequestHeaders to fail somewhere.

We moved the test application under `git.example.io/rune/rune` adjacent to the vendor folder and it worked just fine.

**Comment by zikes** [comment] 2018-03-28 04:30
Yeah it was `contextkeys`, specifically the `contextKeys` custom type which Go would consider different between vendored and non-vendored Twirp. Changing this to plain `int` fixes this:

```
--- a/internal/contextkeys/keys.go
+++ b/internal/contextkeys/keys.go
@@ -16,10 +16,8 @@
 // without exposing the setters to the outside world.
 package contextkeys
 
-type contextKey int
-
 const (
-       MethodNameKey contextKey = 1 + iota
+       MethodNameKey int = 1 + iota
        ServiceNameKey
        PackageNameKey
        StatusCodeKey
```

I made the above change in both our vendored twirp and the one in `$GOPATH` which the test application uses, and resolved the issue.

**Comment by spenczar** [comment] 2018-04-01 18:24
Hi, thanks for the clear issue!

It sounds like the root cause here is incomplete vendoring. I don't think this is a problem with Twirp, and is not one Twirp should try to resolve; instead, it's something that you'll run into again and again in Go if you import a package which has a `vendor` directory, and you don't strip out that `vendor` directory (this is sometimes called "flattening" the vendor directory).

Nested vendor directories, as you found, result in incompatible type definitions, because `imported/vendor/foo` is not the same as `foo`. This is, in fact, by design. [Here's Russ Cox on the topic](https://groups.google.com/d/msg/golang-dev/WebP4dLV1b0/GiSXbjQXEgAJ):

>The problem here is that import "a" means something different in gbv/vendor/b.go as it does in gbv/foo.go. In gbv/vendor/b.go it means "gbv/vendor/b/vendor/a". In gbv/foo.go it means "gbv/vendor/a". 
>
>The fact that the imports mean different things is working as designed.
>
>[...]
>
>As others have noted, tools might help you avoid creating this state or resolve it. You responded that you don't want to have to use tools. You don't. It's perfectly fine to build these trees by hand, provided you realize what the creation of these directories says and make sure not to say something that doesn't work (or take responsibility for fixing it when you do).

(that whole thread is informative, by the way, and so is [this one](https://groups.google.com/forum/#!msg/golang-nuts/AnMr9NL6dtc/UnyUUKcMCAAJ)).

So, the right solution is to use a tool like [`dep`](https://github.com/golang/dep) manage the process. If you import a package which is relying upon a `vendor` directory, you **must** also use a `vendor` directory yourself. Otherwise, types will be incompatible all over the place. It's just the cost of doing business with Go, at least today. Maybe the proposed [vgo](https://github.com/golang/proposal/blob/master/design/24301-versioned-go.md) changes to the Go toolchain will help alleviate this by removing the `vendor` directory entirely, we'll see.

**Closed by spenczar** 2018-04-01 18:24 UTC
